### ISSUE TITLE
i am having error when trying to deploy it

### ISSUE THREAD

**Issue by nijeesh4all** [kimmy214/gitee-pages#1]
```##[error]File not found: '/home/runner/work/_actions/upcwangying/gitee-pages/v0.0.1/lib/main.js'```

action on my action file 

```
- name: deploy to github pages
        uses: upcwangying/gitee-pages@v0.0.1
        with:
           repo:  https://github.com/nijeesh4all/nijeesh4all.github.io
           target_branch: master
           build_dir: dist
```
